#ifndef TIPO_INSTRUCCIONES_H_INCLUDED
#define TIPO_INSTRUCCIONES_H_INCLUDED

typedef enum {LEER, MOSTRAR, ASIG_VAL, ASIG_VAR, FUNC_VALVAL, FUNC_VARVAR, FUNC_VARVAL, FUNC_VALVAR} tipo_instruccion;


#endif // TIPO_INSTRUCCIONES_H_INCLUDED
