#ifndef TIPO_INSTRUCCIONES_H_INCLUDED
#define TIPO_INSTRUCCIONES_H_INCLUDED

typedef enum {LEER, MOSTRAR, ASIGVAL, ASIGVAR, FUNCVALVAL, FUNCVARVAR, FUNCVARVAL, FUNCVALVAR} tipoInstruccion;


#endif // TIPO_INSTRUCCIONES_H_INCLUDED
